on: [push, pull_request]
name: CI
env:
  GOPRIVATE: github.com/chinese-room-solutions/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Install
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"
          check-latest: true
      - name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.898
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          # --concurrency 0 automatically matches Linux container CPU quota.
          args: --timeout 10m --concurrency 0

      - name: Make all
        run: make all

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::error::Generated files are out of date. Please rerun 'make all'."
            git diff
            exit 1
          fi
